version: '2.2'

services:
  kafka:
      network_mode: host
      image: wurstmeister/kafka:2.12-2.3.0
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 137.157.211.55
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_ZOOKEEPER_CONNECT: 137.157.211.55:2181
        KAFKA_MESSAGE_MAX_BYTES: 200000000
        KAFKA_SOCKET_REQUEST_MAX_BYTES: 200000000
        KAFKA_BROKER_ID: 0
        KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 3600000 # 1 hour
        KAFKA_LOG_RETENTION_MS: 3600000 # keep for 1 hour
        KAFKA_CREATE_TOPICS: "TEST_writerCommand:1:1,TEST_writerStatus:1:1,sics-stream:1:1,sics-units:1:1"
      security_opt:
        - label:disable
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /opt/tmp/kafka:/kafka
  
  zookeeper:
      network_mode: host
      image: zookeeper:3.4
      ports:
        - '2181:2181'

  graphite:
    network_mode: host
    image: graphiteapp/graphite-statsd:latest
    container_name: graphite
    restart: always
    ports:
      - '80:80'
      - '2003-2004:2003-2004'
      - '2023-2024:2023-2024'
      - '8125:8125/udp'
      - '8126:8126'

  efu:
    network_mode: host
    image: event-formation-unit:latest
    depends_on:
      - kafka
      - graphite
    #  - filewriter
    environment:
      EXECUTABLE: efu
      OPT_ARGS: -d ./efu/modules/ansto -f /configs/pelican.json -i 137.157.211.55 -p 9010 --nohwcheck
    hostname: efu
    volumes:
        - /opt/ansto/event-formation-unit/src/modules/ansto/configs:/configs
    #ports:
    #  - "8889:8888" # So can query efu stats on localhost:8889

  # efu-udpgen:
  #   network_mode: host
  #   image: event-formation-unit:latest
  #   depends_on:
  #     - efu
  #   environment:
  #     EXECUTABLE: udpgen_ansto
  #     OPT_ARGS: -d mcpd8 -c /configs/mcpd8.json -i 137.157.211.49 -p 9010 -t 10000
  #   volumes:
  #       - /opt/ansto/event-formation-unit/src/ansto/configs:/configs

  filewriter:
    network_mode: host
    image: kafkatonexus:latest
    restart: always
    depends_on: 
      - kafka
    environment:
      EXECUTABLE: kafka-to-nexus
      OPT_ARGS: -c /config/file_writer_ansto.ini
    security_opt:
      - label:disable
    volumes:
        - /opt/tmp/filewriter/config:/config/
        - /opt/tmp/filewriter/output-files/:/output-files/
        - /opt/tmp/filewriter/logs/:/logs/